anomaly:
  contamination: 0.15
  method: isolation_forest
clustering:
  method: kmeans
  n_clusters: null
  random_state: 42
data:
  input_csv: data/rdkk_dataset.csv
  output_dir: output/
models:
  anomaly_file: anomaly_model.pkl
  features_file: features.json
  kmeans_file: kmeans.joblib
  output_dir: models/
  scaler_file: scaler.joblib
standar_pupuk:
  BAWANG MERAH:
    NPK:
      max: 530.0
      min: 0.0
    Organik:
      max: 1000.0
      min: 0.0
    Urea:
      max: 250.0
      min: 0.0
  # BAWANG_MERAH:
  #   NPK:
  #     max: 350.0
  #     min: 0.0
  #   Organik:
  #     max: 1000.0
  #     min: 0.0
  #   Urea:
  #     max: 250.0
  #     min: 0.0
  CABAI:
    NPK:
      max: 400.0
      min: 0.0
    Organik:
      max: 1000.0
      min: 0.0
    Urea:
      max: 250.0
      min: 0.0
  JAGUNG:
    NPK:
      max: 350.0
      min: 0.0
    Organik:
      max: 1000.0
      min: 0.0
    Urea:
      max: 250.0
      min: 0.0
  KAKAO:
    NPK:
      max: 280.0
      min: 0.0
    Organik:
      max: 1000.0
      min: 0.0
    Urea:
      max: 300.0
      min: 0.0
  KOPI:
    NPK:
      max: 860.0
      min: 0.0
    Organik:
      max: 1000.0
      min: 0.0
    Urea:
      max: 250.0
      min: 0.0
  PADI:
    NPK:
      max: 300.0
      min: 0.0
    Organik:
      max: 1000.0
      min: 0.0
    Urea:
      max: 250.0
      min: 0.0
  enabled: true
streamlit:
  layout: wide
  page_icon: ðŸŒ¾
  page_title: RDKK - Analisis Pupuk Subsidi
  theme: light
